name: Depoly

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #  소스코드 불러오기
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and push
        run: |
          docker build \
          --push \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/auto-trade:${{ github.run_number }} .

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_APPLICATION_HOST }}
          username: ${{ secrets.OCI_APPLICATION_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: 22
          script: |
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            if [ "$(sudo docker ps -a -q -f name=auto-trade)" ]; then
              sudo docker stop auto-trade
              sudo docker rm auto-trade
            fi
            sudo docker run -d -p 5000:5000 \
            --name auto-trade ${{ secrets.DOCKERHUB_USERNAME }}/auto-trade:${{ github.run_number }}
