name: Depoly

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #  소스코드 불러오기
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and push
        run: |
          docker build \
          --push \
          --platform linux/amd64 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/auto-trade:${{ github.ref_name }} .

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.OCI_APPLICATION_HOST }}
          username: ${{ secrets.OCI_APPLICATION_USERNAME }}
          key: ${{ secrets.OCI_SSH_KEY }}
          port: 22
          script: |
            cd /home/${{ secrets.OCI_APPLICATION_USERNAME }}
            if ls | grep auto-trade; then
              cd auto-trade
              git pull --recurse-submodules
            else 
              git clone --recurse-submodules https://github.com/sandropark/auto-trade.git
              cd auto-trade
            fi
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker compose up -d
